In [1]:
import numpy as np

In [6]:
captions_file = "../../vote_captions_bigram.backup.pickle"
captions = np.load(captions_file)

In [8]:
captions[1]

([array([  1,   4, 164,   6, 769,  10,   4, 164,   6, 769,  15,   5,   4,
          26,   2]),
  array([  1,   4, 164,   6, 769,  15,   5,   4,  26,   2]),
  array([  1,   4, 164,   6, 769,  15,   5,  34,   6,   4,  26,   2]),
  array([  1,   4, 164,   6, 769,  15,   5,   4, 100,  26,   2]),
  array([  1,   4, 164,   6, 769,  27,  11,  15,   5,   4,  26,   2])],
 [0.00013661629900795327,
  0.0029771133116083663,
  0.0009937856776175604,
  0.0009405587536410049,
  0.0009060354150210453])